### ISSUE TITLE
Add function shuffle<A,B,C,D>()

### ISSUE THREAD

**Issue by hrabalik** [hrabalik/simdee#12]
The introduction of this function could enable an efficient implementation of matrix multiplication using only the library facilities.

The number of template arguments of `shuffle()` would depend on the width of the SIMD type -- therefore all code that uses it becomes non-portable unless fixed-width types are available (see #8).

**Comment by tufak** [comment]
Implementing this for `dual` will be troublesome to say the least. Seems impossible at this point.
